# Generated by Django 2.2.5 on 2021-07-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_board_mainphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
