# Generated by Django 2.2.5 on 2021-07-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210704_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
            ],
        ),
    ]
