# Generated by Django 2.2.5 on 2021-07-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_model_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kmeans',
            field=models.IntegerField(null=True),
        ),
    ]
